add pylint

diff --git a/2-Build_and_Deploy/Jenkinsfile b/2-Build_and_Deploy/Jenkinsfile
--- a/2-Build_and_Deploy/Jenkinsfile
+++ b/2-Build_and_Deploy/Jenkinsfile
@@ -10,16 +10,42 @@ pipeline {
                  '''
              }
          }
-         stage('Lint HTML') {
-              steps {
-                  sh 'tidy -q -e *.html'
-              }
-         }
-        stage('test1') {
-             steps {
-                echo 'Hello World'
-                snsPublish(topicArn: 'arn:aws:sns:us-west-2:086340503613:jenkinspratice', subject: 'PraticebuildOK', message: 'build is ok')
-      }
+        stage('Lint Dockerfile') {
+            steps {
+                script {
+                    sh 'docker run --rm -i hadolint/hadolint < Dockerfile | tee -a hadolint.txt'
+                    sh '''
+                        lintErrors=$(stat --printf="%s"  hadolint.txt)
+                        if [ "$lintErrors" -gt "0" ]; then
+                            echo "Errors linting Dockerfile"
+                            cat hadolint.txt
+                            exit 1
+                        else
+                                echo "Done linting Dockerfile"
+                            fi
+                        '''
+                    }
+                }
+            }
+ stage('lint'){
+       steps {
+        sh "virtualenv --python=/usr/bin/python3 venv"
+        sh "export TERM='linux'"  
+        sh 'pylint --rcfile=pylint.cfg funniest/ $(find . -maxdepth 1 -name "*.py" -print) --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" > pylint.log || echo "pylint exited with $?"'
+        sh "rm -r venv/"
+       
+        echo "linting Success, Generating Report"
+         
+        warnings canComputeNew: false, canResolveRelativePaths: false, defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', messagesPattern: '', parserConfigurations: [[parserName: 'PyLint', pattern: '*']], unHealthy: ''
+       
+       }   
+     }
+ stage('Build docker image') {
+            steps {
+                script {
+                    image = docker.build("msoulie/capstone-project", "-f Dockerfile")
+                }
+            }
         }
       stage('Security Scan') {
               steps { 
